services:
  frontend:
    container_name: pokedex-frontend
    build:
      context: ./pokedex-frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    
  api:
    container_name: pokedex-api
    build:
      context: ./api
      dockerfile: ./Dockerfile 
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - NODE_ENV=development
    
